version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/tools/php-cs-fixer"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/tools/rector"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/tools/phpstan"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/tools/infection"
    schedule:
      interval: "daily"
